### PR TITLE
Delete datasets

### PR DESCRIPTION
**Pull request by sakeerthy**
DELETE methods for
/datasetContents/{dataset_name}
/VSAMdatasetContents/{dataset_name}

### CODE REVIEW

**Comment by ifakhrutdinov** [comment]
Is this a duplicate of #102? If so, why do you need 2?

**Comment by ifakhrutdinov** [comment]
Please provide description.

**Comment by ifakhrutdinov** [comment]
@sakeerthy why are there all these commits that don't belong to this PR? Please rebase your branch.

**Comment by sakeerthy** [comment]
> @sakeerthy why are there all these commits that don't belong to this PR? Please rebase your branch.

**Comment by sakeerthy** [comment]
> @sakeerthy why are there all these commits that don't belong to this PR? Please rebase your branch.

I don't think I have the right permissions to merge staging into this branch, when i run git pull staging, I get 

fatal: 'staging' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ifakhrutdinov** [comment]
What command did you use? Can you copy and paste it here?

**Comment by sakeerthy** [comment]
> What command did you use? Can you copy and paste it here?

git pull staging

**Comment by ifakhrutdinov** [comment]
@sakeerthy 

It's `git pull origin staging` or `git pull upstream staging`, depending where you want to pull from.

https://git-scm.com/docs/git-pull

**Comment by sakeerthy** [comment]
> @sakeerthy
> 
> It's `git pull origin staging` or `git pull upstream staging`, depending where you want to pull from.
> 
> https://git-scm.com/docs/git-pull

It looks doing that didn't get rid of all the other commits

**Comment by ifakhrutdinov** [comment]
I don't know how you were going to use that command to get rid of the commits, I just corrected the syntax so it works.

**Comment by sakeerthy** [comment]
Old duplicate

**Pull request closed without merging**
