### PR TITLE
bring SAMPLIB in line with CUPIDS epic

### PR DESCRIPTION
**Pull request by OnnoVdT**
Since the system won't even show my branch, I can't have a proper pull request so I'm trying with this manual one that has a a zip attached (github won't accept the extension of the files so I can't attach the individual files).
[samplib.zip](https://github.com/zowe/zss/files/3846602/samplib.zip)

As mentioned in issue 94, these are the updates  

    renamed:    ZWESISMS -> ../ZWESISMS

** ZWESISMS is just a copyright header and should not be shipped to customers.
-> move it away from the shipped files

    renamed:    ZWESAUX -> ZWESASTC.jcl

** To avoid complications with SMP/E managed installs we do not allow duplicate file names.
-> loadmod keeps its name, STC changes name

    renamed:    ZWESIS01 -> ZWESISTC.jcl

** To avoid complications with SMP/E managed installs we do not allow duplicate file names.
-> loadmod keeps its name, STC changes name

Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)

    modified:   ZWESASTC.jcl

->reworked to provide additional info, create uniform look & feel for all JCL and use common variable names to simplify customization scripts

    modified:   ZWESISCH

-> fixed faulty comment characters, create uniform look & feel for all PARMLIB members

    modified:   ZWESISTC.jcl

->reworked to provide additional info, create uniform look & feel for all JCL and use common variable names to simplify customization scripts

Untracked files:
(use "git add ..." to include in what will be committed)

    ZWESIPRG

** New: sample PROGxx member

### CODE REVIEW

**Comment by ifakhrutdinov** [comment]
@OnnoVdT  looks like you're trying to merge unrelated commits.

> Since the system won't even show my branch, I can't have a proper pull request so I'm trying with this manual one that has a a zip attached (github won't accept the extension of the files so I can't attach the individual files).

@1000TurquoisePogs can we give @OnnoVdT proper privileges please?

**Comment by 1000TurquoisePogs** [comment]
I just gave privileges to the web UI squad, which may be what was needed here. Otherwise, not sure.

**Comment by ifakhrutdinov** [comment]
@OnnoVdT can you please resolve the conflicts and remove all unrelated commits from the pull-request?

**Comment by 1000TurquoisePogs** [comment]
This appears to have no changes left due to age, so closing.

**Pull request closed without merging**
