### PR TITLE
put datasetjson to zss

### PR DESCRIPTION
**Pull request by joepun76**
Signed-off-by: joepun76 <jouphpun76@gmail.com>

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [x] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [x] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
(https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [x] My changes generate no new warnings

## Testing

tested update dataset member

### CODE REVIEW

**Comment by joepun76** [comment]
Please review. Thanks very much.

**Review by ifakhrutdinov — APPROVED** [review]
LGTM. @joepun76 can you please a PR in zowe-common-c and remove these source there, perhaps with a commit comment quoting the zss commit in which the sources were added to the zss repo.

**Comment by joepun76** [comment]
@ifakhrutdinov add the deps/zowe-common-c.

Please check if ok.  This is my first time did it. Thanks very much.

**Comment by ifakhrutdinov** [comment]
LGTM

**Pull request merged**
