### PR TITLE
merge SAF IDT changes from v1

### PR DESCRIPTION
**Pull request by achmelo**
## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made
- [ ] Relevant update to CHANGELOG.md
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

### CODE REVIEW

**Review by ifakhrutdinov — APPROVED** [review]
I've compared the original diff and the new diff and the only difference is the sub-module reference hash.

@JoeNemo anything v2 specific this PR might have missed? E.g. make sure 64-bit would work.

**Review by JoeNemo — APPROVED** [review]
Seems ok and was reviewed  in 1.x

**Comment by ifakhrutdinov** [comment]
@achmelo can you please pick up the origin/v2.x/staging branch in the zowe-common-c deps? Currently, this PR seems to be pointing to a zowe-common-c commit in **your** repo, not zowe/zowe-common-c.

**Review by ifakhrutdinov — CHANGES_REQUESTED** [review]
The submodule commit needs to be corrected. See my previous comment.

**Comment by achmelo** [comment]
> @achmelo can you please pick up the origin/v2.x/staging branch in the zowe-common-c deps? Currently, this PR seems to be pointing to a zowe-common-c commit in **your** repo, not zowe/zowe-common-c.

It is pointing to the commit that you have merged in zowe-common-c, so it is now also in zowe-common-c repo

**Comment by achmelo** [comment]
> The submodule commit needs to be corrected. See my previous comment.

I see there are more changes after this commit in common-c so I will change it so it points to the head of staging branch

**Review by ifakhrutdinov — APPROVED** [review]

**Pull request closed without merging**
