### PR TITLE
Feature/jwt logging

### PR DESCRIPTION
**Pull request by adityadr-joy**
## Proposed changes

Changes:

- Reading jwt log level configuration (_zss.jwtTrace) and calling respective trace definition to set these log level.
- Update the pointer to the zowe-common-c submodule

This PR depends upon the following PRs:
https://github.com/zowe/zowe-common-c/pull/232

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.

## PR Checklist
Please delete options that are not relevant.
- [x] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
- [x] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made
- [ ] Relevant update to CHANGELOG.md
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

### CODE REVIEW

**Review by 1000TurquoisePogs — APPROVED** [review]
Looks good to me based on https://github.com/zowe/zowe-common-c/pull/232#pullrequestreview-741197305 but I still need to do a test.

**Review by lchudinov — APPROVED** [review]
I checked that it works good. @adityadr-joy please resolve the conflict.

**Comment by lchudinov** [comment]
It looks like the pointer to zowe-common-c is incorrect because `httpserver.c` wasn't changed by Aditya.
image

**Review by DivergentEuropeans — APPROVED** [review]
Changes have been fixed

**Review by 1000TurquoisePogs — APPROVED** [review]

**Pull request merged**
